name: flutter_drug
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0.3+3

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cool_ui:  ^0.3.1
  device_info: ^0.4.1+4
  package_info: ^0.4.0+13
  # 屏幕适配
  flutter_screenutil: ^0.7.0
  # State
  provider: ^3.2.0
  # UI
  oktoast: ^2.2.0
  # refresh
  pull_to_refresh: ^1.5.7
  # banner
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.0.0-rc
  # Data
  dio: ^3.0.7
  # 本地存储
  shared_preferences: ^0.5.6
  localstorage: ^2.0.0
  # event_bus
  event_bus: ^1.1.0
  url_launcher: ^5.4.1
  path_provider: ^1.5.1
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  webview_flutter: ^0.3.18+1
  # 二维码
  qr_flutter: ^3.0.1
  # 字母筛选
  azlistview: ^0.1.2
  lpinyin: ^1.0.7
  # 小红点
  badges: ^1.1.0
  # 图片选择
  image_picker: ^0.6.2+3
  # 图片缩放
  photo_view: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
#  assets:
#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/city.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
